vim.opt.number=true
vim.opt.relativenumber=true
vim.opt.shiftwidth=2
vim.opt.tabstop=2
vim.opt.softtabstop=2
vim.opt.expandtab=true -- use space for make tabs
vim.opt.swapfile=false -- no swap file
vim.opt.mouse='a' -- allow mousejj
vim.opt.ignorecase=true -- ignore sensitive case for searching for example
vim.opt.smartcase=true -- ignore uppercase unless the search term has an uppercase letter
vim.opt.hlsearch=false -- highligh the result of the previous search
vim.opt.wrap=true -- makes the text of long lines always visible
vim.opt.breakindent=true -- preserve the indentation of a virtual line
vim.opt.clipboard="unnamedplus" -- use the clipboard register for all operations except yank
vim.opt.autoindent=true -- copy indent from current line when starting a new line
vim.opt.encoding="utf-8" -- sets teh char encoding used inside nvim
vim.opt.fileencoding="utf-8" -- sets the char encoding for the file of this buffer
vim.opt.title=true -- show the title on window with the value of titlestring
vim.opt.wildmenu=true -- command line completion operates in an enhanced mode
vim.opt.showcmd=true -- show partial command in the last line of the screen
--vim.opt.showmatch=true -- when bracket is inserted briefly jump to the matching one
